// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vKzW7roadhCU2MH7WoNwmYulRz3z_cQ',
    appId: '1:387202223471:web:de0c475224897b34ab2c9a',
    messagingSenderId: '387202223471',
    projectId: 'best-of-nepal',
    authDomain: 'best-of-nepal.firebaseapp.com',
    storageBucket: 'best-of-nepal.firebasestorage.app',
    measurementId: 'G-W7RQBGZXKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMq20Wc9CoA6gqgy9bJX1M9Yxd53MUU0U',
    appId: '1:387202223471:android:00dc37479300bf5bab2c9a',
    messagingSenderId: '387202223471',
    projectId: 'best-of-nepal',
    storageBucket: 'best-of-nepal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaL_pz036On_WzcDOmyQzj2S70WecApnw',
    appId: '1:387202223471:ios:a665c0be1500a792ab2c9a',
    messagingSenderId: '387202223471',
    projectId: 'best-of-nepal',
    storageBucket: 'best-of-nepal.firebasestorage.app',
    iosBundleId: 'com.example.bestOfNepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaL_pz036On_WzcDOmyQzj2S70WecApnw',
    appId: '1:387202223471:ios:a665c0be1500a792ab2c9a',
    messagingSenderId: '387202223471',
    projectId: 'best-of-nepal',
    storageBucket: 'best-of-nepal.firebasestorage.app',
    iosBundleId: 'com.example.bestOfNepal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-vKzW7roadhCU2MH7WoNwmYulRz3z_cQ',
    appId: '1:387202223471:web:7ef56f18d9f31f99ab2c9a',
    messagingSenderId: '387202223471',
    projectId: 'best-of-nepal',
    authDomain: 'best-of-nepal.firebaseapp.com',
    storageBucket: 'best-of-nepal.firebasestorage.app',
    measurementId: 'G-EMBG6JD488',
  );
}
